spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect # Optional in Spring Boot 3