spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect # Optional in Spring Boot 3
app:
  jwt:
    secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
    expiration-milliseconds: '604800000'
